from enum import Enum


class PBMSErrorCodes(str, Enum):
    INVALID_REQUEST = "INVALID_REQUEST"
    PROGRAM_NOT_FOUND = "NOT_FOUND"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    DB_ERROR = "DB_ERROR"
